site_name: AMOR-SEGB Documentation
site_description: Semantic Ethical Glass Box (SEGB) is a framework for generating semantic logs from human-robot interactions, enabling ethical analysis and transparency in robotic systems.
repo_url: https://github.com/gsi-upm/semantic_ethical_glass_box
repo_name: gsi-upm/semantic_ethical_glass_box

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Centralized Deployment: deployment_centralized.md
  - semantic_log_generator:
      - Installation: semantic_log_generator_installation.md
      - Usage: semantic_log_generator_usage.md
      - Real-World Integration Example: semantic_log_generator_real_world_integration.md
      - TTL Internals: ttl_generation_internals.md
  - Web Observability: web_observability.md
  - Backend:
      - Shared Context: backend/shared_context.md
  - Monorepo Structure: monorepo_structure.md
