"""Basic ARI mock for the SEGB demo scenario."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta

from rdflib import URIRef

from semantic_log_generator import ActivityKind, EmotionScore, SemanticSEGBLogger
from semantic_log_generator.namespaces import EMOML, ORO


@dataclass(slots=True)
class AriMockResult:
    """Semantic artifacts generated by ARI during the utterance flow."""

    shared_event_uri: URIRef
    listening_activity_uri: URIRef
    observation_message_uri: URIRef
    decision_activity_uri: URIRef
    response_message_uri: URIRef
    emotion_from_speech_activity_uri: URIRef
    emotion_from_face_before_activity_uri: URIRef
    emotion_from_face_after_activity_uri: URIRef


@dataclass(slots=True)
class AriDetectionResult:
    """Semantic artifacts generated by ARI during human entry detection."""

    shared_event_uri: URIRef
    detection_activity_uri: URIRef
    detection_observation_uri: URIRef


@dataclass(slots=True)
class AriEmotionModels:
    text_model_uri: URIRef
    face_model_uri: URIRef


def ari_detect_human_entry(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    observed_at: datetime,
) -> AriDetectionResult:
    """Logs ARI vision-based detection when Maria enters the room."""
    shared_event_uri = logger.get_shared_event_uri(
        event_kind="human_entry",
        observed_at=observed_at,
        subject=human_uri,
        modality="vision",
    )

    detection_activity_uri = logger.log_activity(
        activity_id="ari_human_detection_1",
        activity_kind=ActivityKind.HUMAN_DETECTION,
        label="ARI detects Maria entering the room",
        started_at=observed_at,
        ended_at=observed_at + timedelta(seconds=1),
        related_shared_events=[shared_event_uri],
    )
    detection_observation_uri = logger.log_observation(
        observation_id="ari_human_entry_1",
        label="Maria entry observed by ARI",
        generated_by_activity=detection_activity_uri,
        related_shared_event=shared_event_uri,
        confidence=0.95,
    )

    return AriDetectionResult(
        shared_event_uri=shared_event_uri,
        detection_activity_uri=detection_activity_uri,
        detection_observation_uri=detection_observation_uri,
    )


def _register_emotion_models(logger: SemanticSEGBLogger) -> AriEmotionModels:
    text_model_uri = logger.register_ml_model(
        "emotion_text_classifier_v1",
        label="Emotion Text Classifier",
        version="1.0",
    )
    face_model_uri = logger.register_ml_model(
        "face_emotion_cnn_v1",
        label="Face Emotion CNN",
        version="1.2",
    )
    return AriEmotionModels(text_model_uri=text_model_uri, face_model_uri=face_model_uri)


def _log_emotion_from_speech(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    observed_at: datetime,
    shared_event_uri: URIRef,
    listening_activity_uri: URIRef,
    observation_message_uri: URIRef,
    model_uri: URIRef,
) -> URIRef:
    emotion_from_speech_activity_uri = logger.log_activity(
        activity_id="ari_emotion_from_speech_1",
        activity_kind=ActivityKind.EMOTION_ANALYSIS,
        label="ARI detects sadness from Maria speech content",
        started_at=observed_at + timedelta(seconds=1),
        ended_at=observed_at + timedelta(seconds=2),
        triggered_by_activity=listening_activity_uri,
        triggered_by_entity=observation_message_uri,
        related_shared_events=[shared_event_uri],
        used_entities=[observation_message_uri],
        used_models=[model_uri],
    )
    logger.log_emotion_annotation(
        source_activity=emotion_from_speech_activity_uri,
        targets=[human_uri],
        emotions=[EmotionScore(category=EMOML.big6_sadness, intensity=0.84, confidence=0.92)],
        emotion_model=EMOML.big6,
    )
    return emotion_from_speech_activity_uri


def _log_emotion_from_face_before_response(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    observed_at: datetime,
    shared_event_uri: URIRef,
    model_uri: URIRef,
) -> URIRef:
    face_before_observation_uri = logger.log_observation(
        observation_id="ari_face_before_response_1",
        label="Maria face snapshot before ARI response",
        related_shared_event=shared_event_uri,
        confidence=0.90,
    )

    emotion_from_face_before_activity_uri = logger.log_activity(
        activity_id="ari_emotion_from_face_before_1",
        activity_kind=ActivityKind.EMOTION_ANALYSIS,
        label="ARI detects sadness from face emotion analysis",
        started_at=observed_at + timedelta(seconds=2),
        ended_at=observed_at + timedelta(seconds=3),
        triggered_by_entity=face_before_observation_uri,
        related_shared_events=[shared_event_uri],
        used_entities=[face_before_observation_uri],
        used_models=[model_uri],
    )
    logger.log_emotion_annotation(
        source_activity=emotion_from_face_before_activity_uri,
        targets=[human_uri],
        emotions=[EmotionScore(category=EMOML.big6_sadness, intensity=0.78, confidence=0.90)],
        emotion_model=EMOML.big6,
    )
    return emotion_from_face_before_activity_uri


def _log_support_decision(
    *,
    logger: SemanticSEGBLogger,
    observed_at: datetime,
    shared_event_uri: URIRef,
    listening_activity_uri: URIRef,
    observation_message_uri: URIRef,
) -> tuple[URIRef, URIRef]:
    decision_activity_uri = logger.log_activity(
        activity_id="ari_decision_1",
        activity_kind=ActivityKind.DECISION,
        label="ARI decides to provide emotional support",
        started_at=observed_at + timedelta(seconds=3),
        ended_at=observed_at + timedelta(seconds=4),
        triggered_by_activity=listening_activity_uri,
        triggered_by_entity=observation_message_uri,
        related_shared_events=[shared_event_uri],
        used_entities=[observation_message_uri],
    )
    response_message_uri = logger.log_message(
        "Maria, I can see you feel sad. I am here with you and we will get through this together.",
        message_id="ari_response_1",
        generated_by_activity=decision_activity_uri,
        message_types=[ORO.ResponseMessage],
        previous_message=observation_message_uri,
    )
    return decision_activity_uri, response_message_uri


def _log_emotion_from_face_after_response(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    observed_at: datetime,
    shared_event_uri: URIRef,
    decision_activity_uri: URIRef,
    model_uri: URIRef,
) -> URIRef:
    face_after_observation_uri = logger.log_observation(
        observation_id="ari_face_after_response_1",
        label="Maria face snapshot after ARI response",
        related_shared_event=shared_event_uri,
        confidence=0.93,
    )

    emotion_from_face_after_activity_uri = logger.log_activity(
        activity_id="ari_emotion_from_face_after_1",
        activity_kind=ActivityKind.EMOTION_ANALYSIS,
        label="ARI detects happiness after emotional support",
        started_at=observed_at + timedelta(seconds=5),
        ended_at=observed_at + timedelta(seconds=6),
        triggered_by_activity=decision_activity_uri,
        triggered_by_entity=face_after_observation_uri,
        related_shared_events=[shared_event_uri],
        used_entities=[face_after_observation_uri],
        used_models=[model_uri],
    )
    logger.log_emotion_annotation(
        source_activity=emotion_from_face_after_activity_uri,
        targets=[human_uri],
        emotions=[EmotionScore(category=EMOML.big6_happiness, intensity=0.74, confidence=0.93)],
        emotion_model=EMOML.big6,
    )
    return emotion_from_face_after_activity_uri


def ari_handle_human_utterance(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    text: str,
    observed_at: datetime,
) -> AriMockResult:
    """Logs ARI behavior: listen -> sadness analysis -> empathic response -> happiness analysis."""
    shared_event_uri = logger.get_shared_event_uri(
        event_kind="human_utterance",
        observed_at=observed_at,
        subject=human_uri,
        text=text,
        modality="speech",
    )

    listening_activity_uri = logger.log_activity(
        activity_id="ari_listening_1",
        activity_kind=ActivityKind.LISTENING,
        started_at=observed_at,
        ended_at=observed_at + timedelta(seconds=1),
        related_shared_events=[shared_event_uri],
    )

    observation_message_uri = logger.log_message(
        text,
        message_id="ari_heard_1",
        generated_by_activity=listening_activity_uri,
        message_types=[ORO.InitialMessage],
        language="en",
    )
    logger.link_observation_to_shared_event(observation_message_uri, shared_event_uri, confidence=0.95)

    models = _register_emotion_models(logger)
    emotion_from_speech_activity_uri = _log_emotion_from_speech(
        logger=logger,
        human_uri=human_uri,
        observed_at=observed_at,
        shared_event_uri=shared_event_uri,
        listening_activity_uri=listening_activity_uri,
        observation_message_uri=observation_message_uri,
        model_uri=models.text_model_uri,
    )
    emotion_from_face_before_activity_uri = _log_emotion_from_face_before_response(
        logger=logger,
        human_uri=human_uri,
        observed_at=observed_at,
        shared_event_uri=shared_event_uri,
        model_uri=models.face_model_uri,
    )
    decision_activity_uri, response_message_uri = _log_support_decision(
        logger=logger,
        observed_at=observed_at,
        shared_event_uri=shared_event_uri,
        listening_activity_uri=listening_activity_uri,
        observation_message_uri=observation_message_uri,
    )
    emotion_from_face_after_activity_uri = _log_emotion_from_face_after_response(
        logger=logger,
        human_uri=human_uri,
        observed_at=observed_at,
        shared_event_uri=shared_event_uri,
        decision_activity_uri=decision_activity_uri,
        model_uri=models.face_model_uri,
    )

    return AriMockResult(
        shared_event_uri=shared_event_uri,
        listening_activity_uri=listening_activity_uri,
        observation_message_uri=observation_message_uri,
        decision_activity_uri=decision_activity_uri,
        response_message_uri=response_message_uri,
        emotion_from_speech_activity_uri=emotion_from_speech_activity_uri,
        emotion_from_face_before_activity_uri=emotion_from_face_before_activity_uri,
        emotion_from_face_after_activity_uri=emotion_from_face_after_activity_uri,
    )
