"""Basic TIAGo mock for the SEGB demo scenario."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta

from rdflib import URIRef

from semantic_log_generator import ActivityKind, SemanticSEGBLogger
from semantic_log_generator.namespaces import ORO


@dataclass(slots=True)
class TiagoMockResult:
    """Semantic artifacts generated by TIAGo for one human utterance."""

    shared_event_uri: URIRef
    listening_activity_uri: URIRef
    observation_message_uri: URIRef
    engagement_decision_activity_uri: URIRef


@dataclass(slots=True)
class TiagoDetectionResult:
    """Semantic artifacts generated by TIAGo during human entry detection."""

    shared_event_uri: URIRef
    detection_activity_uri: URIRef
    detection_observation_uri: URIRef


def tiago_detect_human_entry(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    observed_at: datetime,
) -> TiagoDetectionResult:
    """Logs TIAGo vision-based detection when Maria enters the room."""
    shared_event_uri = logger.get_shared_event_uri(
        event_kind="human_entry",
        observed_at=observed_at,
        subject=human_uri,
        modality="vision",
    )

    detection_activity_uri = logger.log_activity(
        activity_id="tiago_human_detection_1",
        activity_kind=ActivityKind.HUMAN_DETECTION,
        label="TIAGo detects Maria entering the room",
        started_at=observed_at,
        ended_at=observed_at + timedelta(seconds=1),
        related_shared_events=[shared_event_uri],
    )
    detection_observation_uri = logger.log_observation(
        observation_id="tiago_human_entry_1",
        label="Maria entry observed by TIAGo",
        generated_by_activity=detection_activity_uri,
        related_shared_event=shared_event_uri,
        confidence=0.93,
    )

    return TiagoDetectionResult(
        shared_event_uri=shared_event_uri,
        detection_activity_uri=detection_activity_uri,
        detection_observation_uri=detection_observation_uri,
    )


def tiago_handle_human_utterance(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    text: str,
    observed_at: datetime,
) -> TiagoMockResult:
    """Logs TIAGo behavior: listen and skip response after engagement check."""
    shared_event_uri = logger.get_shared_event_uri(
        event_kind="human_utterance",
        observed_at=observed_at,
        subject=human_uri,
        text=text,
        modality="speech",
    )

    listening_activity_uri = logger.log_activity(
        activity_id="tiago_listening_1",
        activity_kind=ActivityKind.LISTENING,
        started_at=observed_at,
        ended_at=observed_at + timedelta(seconds=1),
        related_shared_events=[shared_event_uri],
    )
    observation_message_uri = logger.log_message(
        text,
        message_id="tiago_heard_1",
        generated_by_activity=listening_activity_uri,
        message_types=[ORO.InitialMessage],
        language="en",
    )
    logger.link_observation_to_shared_event(observation_message_uri, shared_event_uri, confidence=0.90)

    engagement_decision_activity_uri = logger.log_activity(
        activity_id="tiago_engagement_check_1",
        activity_kind=ActivityKind.DECISION,
        label="Engagement check: Maria addressed ARI, TIAGo does not respond",
        started_at=observed_at + timedelta(seconds=1),
        ended_at=observed_at + timedelta(seconds=2),
        triggered_by_activity=listening_activity_uri,
        triggered_by_entity=observation_message_uri,
        related_shared_events=[shared_event_uri],
        used_entities=[observation_message_uri],
    )

    return TiagoMockResult(
        shared_event_uri=shared_event_uri,
        listening_activity_uri=listening_activity_uri,
        observation_message_uri=observation_message_uri,
        engagement_decision_activity_uri=engagement_decision_activity_uri,
    )
