"""Use case 01: basic cross-robot interaction with optional publication to SEGB API."""

from __future__ import annotations

if __package__ in (None, ""):
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from examples.simulations.bootstrap import configure_pythonpath

configure_pythonpath()

import argparse
import json
import os
import warnings
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from rdflib import Graph, URIRef

from examples.mocks.ari_mock import AriDetectionResult, AriMockResult, ari_detect_human_entry, ari_handle_human_utterance
from examples.mocks.tiago_mock import TiagoDetectionResult, TiagoMockResult, tiago_detect_human_entry, tiago_handle_human_utterance
from examples.simulations.cli_common import add_publish_arguments, add_ttl_output_arguments, graph_to_ttl_text, write_ttl_output
from semantic_log_generator import (
    HTTPSharedContextResolver,
    SEGBPublisher,
    SemanticSEGBLogger,
    SharedEventPolicy,
    SharedEventResolver,
)

ARI_NAMESPACE = "https://gsi.upm.es/segb/robots/ari/v1/"
TIAGO_NAMESPACE = "https://gsi.upm.es/segb/robots/tiago/v1/"
DEFAULT_PUBLISH_URL = "http://localhost:5000"


@dataclass(slots=True)
class SimulationResult:
    """Artifacts generated by one base interaction."""

    graph: Graph
    human_uri: URIRef
    entry_shared_event_uri: URIRef
    shared_event_uri: URIRef
    ari_observation_uri: URIRef
    tiago_observation_uri: URIRef
    ari_response_uri: URIRef
    ari_namespace: str
    tiago_namespace: str


@dataclass(slots=True)
class PublishConfig:
    """Configuration used to publish logs to SEGB API."""

    base_url: str
    token: str | None = None
    user: str | None = None
    queue_file: str | None = None
    timeout_seconds: float = 20.0
    verify_tls: bool = True


def build_loggers(
    *,
    shared_event_resolver: SharedEventResolver | None = None,
) -> tuple[Graph, SemanticSEGBLogger, SemanticSEGBLogger]:
    """Builds an isolated in-memory graph and one logger per robot."""
    graph = Graph()
    policy = SharedEventPolicy(
        namespace="https://gsi.upm.es/segb/shared-events/",
        time_bucket_seconds=2,
    )
    ari_logger = SemanticSEGBLogger(
        base_namespace=ARI_NAMESPACE,
        robot_id="ari1",
        robot_name="ARI",
        graph=graph,
        namespace_prefix="ari",
        compact_resource_ids=True,
        shared_event_policy=policy,
        shared_event_resolver=shared_event_resolver,
    )
    tiago_logger = SemanticSEGBLogger(
        base_namespace=TIAGO_NAMESPACE,
        robot_id="tiago1",
        robot_name="TIAGo",
        graph=graph,
        namespace_prefix="tiago",
        compact_resource_ids=True,
        shared_event_policy=policy,
        shared_event_resolver=shared_event_resolver,
    )
    return graph, ari_logger, tiago_logger


def _run_entry_detection(
    *,
    ari_logger: SemanticSEGBLogger,
    tiago_logger: SemanticSEGBLogger,
    human_uri: URIRef,
    observed_at: datetime,
) -> tuple[AriDetectionResult, TiagoDetectionResult]:
    ari_entry_result = ari_detect_human_entry(
        logger=ari_logger,
        human_uri=human_uri,
        observed_at=observed_at,
    )
    tiago_entry_result = tiago_detect_human_entry(
        logger=tiago_logger,
        human_uri=human_uri,
        observed_at=observed_at,
    )
    if ari_entry_result.shared_event_uri != tiago_entry_result.shared_event_uri:
        raise RuntimeError("Shared context mismatch: ARI and TIAGo should resolve the same human-entry URI.")
    return ari_entry_result, tiago_entry_result


def _run_utterance_flow(
    *,
    ari_logger: SemanticSEGBLogger,
    tiago_logger: SemanticSEGBLogger,
    human_uri: URIRef,
    text: str,
    observed_at: datetime,
) -> tuple[AriMockResult, TiagoMockResult]:
    ari_result = ari_handle_human_utterance(
        logger=ari_logger,
        human_uri=human_uri,
        text=text,
        observed_at=observed_at,
    )
    tiago_result = tiago_handle_human_utterance(
        logger=tiago_logger,
        human_uri=human_uri,
        text=text,
        observed_at=observed_at,
    )
    if ari_result.shared_event_uri != tiago_result.shared_event_uri:
        raise RuntimeError("Shared context mismatch: ARI and TIAGo should resolve the same URI.")
    return ari_result, tiago_result


def run_basic_simulation(*, shared_event_resolver: SharedEventResolver | None = None) -> SimulationResult:
    """Runs one interaction scenario.

    Scenario:
    - Maria enters the room and both robots detect her.
    - Maria tells ARI she feels sad.
    - ARI detects sadness (speech + face), responds with support, then detects happiness.
    - TIAGo listens, evaluates engagement, and does not respond.
    """
    graph, ari_logger, tiago_logger = build_loggers(shared_event_resolver=shared_event_resolver)

    maria_uri = ari_logger.register_human("maria", first_name="Maria")
    entry_observed_at = datetime.now(timezone.utc)
    speech_observed_at = entry_observed_at + timedelta(seconds=4)

    ari_entry_result, _ = _run_entry_detection(
        ari_logger=ari_logger,
        tiago_logger=tiago_logger,
        human_uri=maria_uri,
        observed_at=entry_observed_at,
    )

    text = "ARI, I feel sad because I just received bad news."
    ari_result, tiago_result = _run_utterance_flow(
        ari_logger=ari_logger,
        tiago_logger=tiago_logger,
        human_uri=maria_uri,
        text=text,
        observed_at=speech_observed_at,
    )

    return SimulationResult(
        graph=graph,
        human_uri=maria_uri,
        entry_shared_event_uri=ari_entry_result.shared_event_uri,
        shared_event_uri=ari_result.shared_event_uri,
        ari_observation_uri=ari_result.observation_message_uri,
        tiago_observation_uri=tiago_result.observation_message_uri,
        ari_response_uri=ari_result.response_message_uri,
        ari_namespace=ARI_NAMESPACE,
        tiago_namespace=TIAGO_NAMESPACE,
    )


def run_simulation() -> SimulationResult:
    """Backward-compatible alias. Prefer `run_basic_simulation()`."""
    warnings.warn(
        "run_simulation() is deprecated; use run_basic_simulation(). It will be removed in v1.1.0.",
        DeprecationWarning,
        stacklevel=2,
    )
    return run_basic_simulation()


def run_professional_ros2_mock_simulation() -> SimulationResult:
    """Backward-compatible alias kept for existing callers/tests."""
    warnings.warn(
        "run_professional_ros2_mock_simulation() is deprecated; use run_basic_simulation(). "
        "It will be removed in v1.1.0.",
        DeprecationWarning,
        stacklevel=2,
    )
    return run_basic_simulation()


def publish_graph(graph: Graph, *, config: PublishConfig) -> dict[str, Any]:
    """Clears previous KG content and publishes an RDF graph."""
    publisher = SEGBPublisher(
        base_url=config.base_url,
        token=config.token,
        default_user=config.user,
        timeout_seconds=config.timeout_seconds,
        verify_tls=config.verify_tls,
        queue_file=config.queue_file,
    )
    cleanup_response = publisher.delete_all_ttls(user=config.user)
    publish_response = publisher.publish_graph(graph, user=config.user)
    return {
        "published": True,
        "cleanup_response": cleanup_response,
        "publish_endpoint": f"{config.base_url.rstrip('/')}/ttl",
        "publish_response": publish_response,
        "graph_triplet_count": len(graph),
    }


def publish_simulation_result(simulation_result: SimulationResult, *, config: PublishConfig) -> dict[str, Any]:
    """Publishes the simulation graph into SEGB backend."""
    return publish_graph(simulation_result.graph, config=config)


def build_publish_config_from_args(args: argparse.Namespace) -> PublishConfig | None:
    """Builds `PublishConfig` from CLI arguments and environment variables."""
    base_url = args.publish_url or os.getenv("SEGB_API_URL") or DEFAULT_PUBLISH_URL
    if not base_url:
        return None

    token = args.token if args.token is not None else os.getenv("SEGB_API_TOKEN")
    user = args.user if args.user is not None else os.getenv("SEGB_LOG_USER")
    queue_file = args.queue_file if args.queue_file is not None else os.getenv("SEGB_QUEUE_FILE")
    timeout_env = os.getenv("SEGB_PUBLISH_TIMEOUT")
    timeout_seconds = args.timeout_seconds if args.timeout_seconds is not None else float(timeout_env or 20.0)
    verify_tls = not args.insecure

    return PublishConfig(
        base_url=base_url,
        token=token,
        user=user,
        queue_file=queue_file,
        timeout_seconds=timeout_seconds,
        verify_tls=verify_tls,
    )


def build_shared_event_resolver(
    publish_config: PublishConfig | None,
) -> SharedEventResolver | None:
    if publish_config is None:
        return None

    return HTTPSharedContextResolver(
        base_url=publish_config.base_url,
        token=publish_config.token,
        timeout_seconds=min(5.0, publish_config.timeout_seconds),
        verify_tls=publish_config.verify_tls,
        raise_on_error=True,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run use case 01 (basic interaction), optionally publish to SEGB, and optionally export Turtle."
        )
    )
    add_ttl_output_arguments(parser)
    add_publish_arguments(parser, include_no_publish=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    publish_config = None if args.no_publish else build_publish_config_from_args(args)
    shared_event_resolver = build_shared_event_resolver(publish_config)

    basic_result = run_basic_simulation(shared_event_resolver=shared_event_resolver)

    if publish_config is not None:
        report = publish_simulation_result(basic_result, config=publish_config)
        print(json.dumps(report, ensure_ascii=True, indent=2))

    ttl_text = graph_to_ttl_text(basic_result.graph)

    output_path = write_ttl_output(ttl_text, args.ttl_output)
    if output_path is not None:
        print(f"Wrote Turtle to: {output_path}")

    print("Use case: 01-basic-interaction")
    print(f"SharedEvent URI: {basic_result.shared_event_uri}")
    print(f"Triples generated: {len(basic_result.graph)}")

    if not args.no_print_ttl:
        print(ttl_text)


if __name__ == "__main__":
    main()
